# Generated by Django 5.0.2 on 2024-03-05 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventories",
            fields=[
                ("InventoryID", models.AutoField(primary_key=True, serialize=False)),
                ("InventoryName", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                ("ItemID", models.AutoField(primary_key=True, serialize=False)),
                ("ItemName", models.CharField(max_length=300)),
                ("ItemDescription", models.CharField(max_length=500)),
                ("ItemQuantity", models.IntegerField()),
                ("ItemLocation", models.CharField(max_length=300)),
                (
                    "InventoryID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="StashApp.inventories",
                    ),
                ),
            ],
        ),
    ]
